### ISSUE TITLE
null pointer exception is thrown in two player mode sometimes

### ISSUE THREAD

**Issue by zzeng** [UCSB-CS56-Projects/cs56-games-hangman#44]
The null pointer exception will be thrown if the user enters two player mode without inputting a mystery word.

**Comment by makhamzadeh** [comment]
75 points

**Comment by arda-** [comment]
W16 OK

**Comment by MadRubicant** [comment]
F16 CLOSED: There doesn't appear to be a 2-player mode

**Comment by arda-** [comment]
@MadRubicant 
though I am no longer part of the class, I noticed you closed quite a few issues because there doesn't seem to be a  two–player mode. Are you sure you've been using the right branch of the repository?

**Comment by MadRubicant** [comment]
Yeah, the only branch I see is master, and I can't find a way to run 2-player mode. It's possible that the code for 2 players never made it into master on the main repo.

**Comment by arda-** [comment]
I remember two player mode not as a connection between two instance of the game on separate computers, but an option selected during the game setup;  one player enters word to be guessed in a text box, instead of it being selected by the computer as in single player mode.

If it was never integrated into master and you think it's a worthwhile set of features for the current class to implement, my instinct is that the version with these issues is in one of the previous students' forks of the project.
